routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin'], function () {
    Route::post('orders/{orderId}/update', 'Backend\ProductsController@orderUpdate')->name('orders.update');
    Route::post('orders/export', 'Backend\ProductsController@exportToExcel')->name('orders.export');
    Voyager::routes();
});
Route::get('/', 'PagesController@index')->name('home');
Route::get('/search', 'PagesController@search')->name('search');
Route::post('/reviews/add','ReviewsController@newReview')->name('reviews.add');

Route::get('/cart','CartController@index')->name('cart.index');

Route::post('/feedback','PagesController@feedback')->name('feedback');
Route::get('/thanks','PagesController@thanks')->name('thanks');

Route::get('/catalog/getCurrent/{slug}','PagesController@getCurrentCategory');
Route::get('/catalog/{categoryId}/products','PagesController@getAjaxProducts')->name('catalog.ajax.products');

Route::get('/cart','CartController@show')->name('cart.index');
Route::get('/cart/getCartContent','CartController@getCartContent');
Route::post('/cart/addToCart/{productId}','CartController@addToCart')->name('cart.add-to-cart');
Route::get('/cart/getCartItems','CartController@getCartItems');
Route::post('/cart/update','CartController@updateCart')->name('cart.update');
Route::post('/cart/remove','CartController@removeFromCart')->name('cart.remove');
Route::get('/cart/clear','CartController@destroyCart');
Route::get('/cart/remove/{itemId}','CartController@removeItem');
Route::get('/checkout','CartController@checkoutIndex')->name('cart.checkout');
Route::post('/checkout/submit','CartController@checkoutSubmit')->name('cart.checkout.submit');
Route::get('/checkout/{orderId}/thanks','CartController@checkoutThanks')->name('cart.checkout.thanks');
//Route::get('/checkout/{orderId}/cardPay','CartController@cardPay')->name('cart.checkout.cardPay');

//Route::get('/checkout/{orderId}/{paymentId}/awaiting','PaymentController@checkoutAwaiting')->name('cart.checkout.awaiting');
//Route::get('/checkout/{orderId}/{paymentId}/checkPaymentStatus','PaymentController@checkOrderPaymentStatus')->name('checkPaymentStatus');

Route::get('/{page}','PagesController@show')->name('pages.show');
Route::get('/{page}/{slug}','PagesController@showInner')->name('pages.inner');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use TCG\Voyager\Traits\Resizable;

class Category extends \TCG\Voyager\Models\Category
{
    use Resizable;
    /**
     * Get the route key for the model.
     *
     * @return string
     */

    public function getRouteKeyName()
    {
        return 'slug';
    }

    protected $dates = ['created_at','updated_at'];


    public function products()
    {
        return $this->hasMany(Product::class)->where('active',true)->orderBy('sort_id');
    }

    public function categories()
    {
        return $this->hasMany(self::class, 'parent_id')->where('active',true)
            ->orderBy('order', 'ASC');
    }

    public function parent()
    {
        return $this->parentId();
    }

    public function getParentsAttribute()
    {
        $parents = collect([]);

        $parent = $this->parent;

        while (!is_null($parent)) {
            $parents->push($parent);
            $parent = $parent->parent;
        }

        return $parents;
    }


    public function getLinkAttribute()
    {
        $categories = $this->parents->reverse();
        $categories->push($this);
        return '/catalog/' . $categories->pluck('slug')->implode('/');

    }

    public function parentId()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

    /**
     * Set the user's first name.
     *
     * @param  string  $value
     * @return void
     */
    public function setThumbnailAttribute($value)
    {
        if ($value) {
            $this->attributes['thumb'] = str_replace('.' . pathinfo(\Voyager::image($value),PATHINFO_EXTENSION), '-small.webp', \Voyager::image($value));
        }else {
            $this->attributes['thumb'] = '/images/nophoto.png';
        }
    }

    public static function scopeSearch($query, $searchTerm)
    {
        return $query->where('name', 'like', '%' .$searchTerm. '%')
            ->orWhere('slug', 'like', '%' .$searchTerm. '%');
    }


    /**
     * Set the user's first name.
     *
     * @param  string  $value
     * @return void
     */
    public function setThumbnailSmallAttribute($value)
    {
        if ($value){
            $this->attributes['thumbnailSmall'] = str_replace('.'.pathinfo(\Voyager::image($value),PATHINFO_EXTENSION),'-small.webp',\Voyager::image($value));
        }else {
            $this->attributes['thumbnailSmall'] = '/images/nophoto.png';
        }
    }
    /**
     * Set the user's first name.
     *
     * @param  string  $value
     * @return void
     */
    public function setWebpAttribute($value)
    {
        if ($value) {
            $this->attributes['webp'] = str_replace('.' . pathinfo(\Voyager::image($value),PATHINFO_EXTENSION), '.webp', \Voyager::image($value));;
        } else {
            $this->attributes['webp'] = '/images/nophoto.png';
        }
    }

    public function getWebpImageAttribute()
    {
        return str_replace('.' . pathinfo(\Voyager::image($this->image),PATHINFO_EXTENSION), '.webp', \Voyager::image($this->image));
    }


    public function getBigThumbAttribute()
    {
        return \Voyager::image($this->getThumbnail($this->image,'big'));
    }

    public function getThumbicAttribute()
    {
        return $this->thumbnail('small','image');
    }
}

resources/views/pages/about.blade.php
@extends('app')
@section('title',(strlen($seoTitle) > 1 ? $seoTitle : $page->title))
@section('seo_title', (strlen($seoTitle) > 1 ? $seoTitle : $page->seo_title))
@section('meta_keywords',(strlen($keywords) > 1 ? $keywords :$page->meta_keywords))
@section('meta_description', (strlen($description) > 1 ? $description : $page->meta_description))
@section('image',env('APP_URL').'/images/og.jpg')
@section('url',url()->current())
@section('page_class','home')
@section('content')
<div class="breadcrumbs">
    @include('partials.breadcrumbs',['title'=>$page->title])
    <h1 class="titleDark">{{$page->title}}</h1>
</div>
<section id="aboutUs">
    <div class="container">
        {!! $page->body !!}
    </div>
</section>
@endsection

resources/views/pages/contacts.blade.php
@extends('app')
@section('title',(strlen($seoTitle) > 1 ? $seoTitle : $page->title))
@section('seo_title', (strlen($seoTitle) > 1 ? $seoTitle : $page->seo_title))
@section('meta_keywords',(strlen($keywords) > 1 ? $keywords :$page->meta_keywords))
@section('meta_description', (strlen($description) > 1 ? $description : $page->meta_description))
@section('image',env('APP_URL').'/images/og.jpg')
@section('url',url()->current())
@section('page_class','home')
@section('content')
    <div class="breadcrumbs">
        @include('partials.breadcrumbs',['title'=>$page->title])
        <h1 class="titleDark">{{$page->title}}</h1>
    </div>
    <style>
        footer .map, footer .contactUs {
            display: none;
        }
    </style>
    <section id="contact" class="py-3 py-md-5">
        <div class="container">
            <div class="row mb-3 mb-md-5">
                <div class="col-12">
                    <div class="map">
                        {!! $map->value !!}
                    </div>
                </div>
            </div>
            <div class="contactInfo p-4 bg-white">
                <div class="row pb-2">
                    <div class="col-lg-5 mb-2 mb-lg-0">
                        <div class="row align-items-center">
                            <div class="col-sm-auto mb-1 mb-sm-0">
                                <strong>Адрес:</strong>
                            </div>
                            <div class="col-sm-auto mb-2 mb-sm-0">
                                <address class="m-0 text-lg-right">{{$address->value}}</address>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row pb-2">
                    <div class="col-lg-7  mb-2 mb-lg-0">
                        <div class="row align-items-center">
                            <div class="col-sm-auto mb-2 mb-sm-0">
                                <strong>Телефон:</strong>
                            </div>
                            @foreach($contacts as $key=>$contact)
                                <div class="col-sm-auto {{$key == 'astana' ? 'mb-2 mb-sm-0' : ''}}">
                                    <p class="m-0 text-lg-right">{{$key == 'astana' ? 'Нур-Султан' : 'Алматы'}}:&nbsp;<a
                                                href="{{$contact->where('type','phone')->first()->link}}">{{$contact->where('type','phone')->first()->value}}</a>
                                    </p>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row pt-2">
                    <div class="col-12">
                        <div class="row align-items-center">
                            <div class="col-sm-auto mb-1 mb-sm-0">
                                <strong>По всем вопросам пишите нам на:</strong>
                            </div>
                            <div class="col-sm-auto mb-2 mb-sm-0">
                                <p class="m-0 text-lg-right"><a
                                            href="{{$email->link}}">{{ $email->value }}</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pt-5">
                {!! $page->body !!}
            </div>
        </div>
    </section>
@endsection

resources/views/pages/reviews.blade.php
@extends('app')
@section('title',(strlen($seoTitle) > 1 ? $seoTitle : $page->title))
@section('seo_title', (strlen($seoTitle) > 1 ? $seoTitle : $page->seo_title))
@section('meta_keywords',(strlen($keywords) > 1 ? $keywords :$page->meta_keywords))
@section('meta_description', (strlen($description) > 1 ? $description : $page->meta_description))
@section('image',env('APP_URL').'/images/og.jpg')
@section('url',url()->current())
@section('page_class','reviews-page')
@section('content')
<div class="breadcrumbs">
    @include('partials.breadcrumbs',['title'=>$page->title])
    <h1 class="titleDark">{{$page->title}}</h1>
</div>
<section id="comments">
    <div class="container">
        <div class="row text-center">
            @foreach($reviews as $k=>$review)
                <div class="col-lg-4 @if($k == 0) col-md-6 @endif @if($k == 1) col-md-6 d-none d-md-block @endif @if ($k == 2) d-none d-lg-block @endif">
                    <div class="commentsImg">
                        <picture>
                            <source srcset="{{$review->webpImage}}" type="image/webp">
                            <source srcset="{{$review->bigThumb}}" type="image/pjpeg">
                            <img src="{{$review->bigThumb}}" alt="{{$review->name}}"
                                 class="img-fluid">
                        </picture>
                    </div>
                    <h4>{{$review->name}}</h4>
                    <h5>{{$review->company}}</h5>
                    <p>{{Str::limit($review->content,275,'...')}}</p>
                    <a href="#" data-toggle="modal" data-target="#modalReview{{$review->id}}" class="readNext">Читать
                        отзыв полностью</a>
                    <div class="modal fade modal-product" id="modalReview{{$review->id}}">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <svg width="17" height="17" viewBox="0 0 17 17" fill="none"
                                         xmlns="http://www.w3.org/2000/svg">
                                        <path d="M1 1L16 16M16 1L1 16" stroke="#AEAEAE" stroke-width="2"
                                              stroke-linecap="round"
                                              stroke-linejoin="round"/>
                                    </svg>
                                </button>
                                <div class="review-content">
                                    <picture>
                                        <source srcset="{{$review->webpImage}}" type="image/webp">
                                        <source srcset="{{$review->bigThumb}}" type="image/pjpeg">
                                        <img src="{{$review->bigThumb}}" alt="{{$review->name}}"
                                             class="img-fluid">
                                    </picture>
                                    <div class="content">
                                        <div class="setTitle">
                                            <h4 class="title">{{$review->name}}</h4>
                                            <p class="company">{{$review->company}}</p>
                                        </div>
                                        <div class="description">{{$review->content}}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        <div class="row pt-5">
            <div class="col-md-12 text-center text-md-center py-2">
                <a href="#" data-target="#modalNewReview" data-toggle="modal" class="btnLight">Добавить отзыв</a>
            </div>
        </div>
    </div>

    <div class="parallax" data-paroller-factor="0.3"
         data-paroller-type="foreground"
         data-paroller-direction="vertical"
         style="width: 356px; height: 183px; right: 30px; bottom: 30%;background: url('img/cbr.png') no-repeat center">
    </div>
</section>
@endsection

resources/views/pages/show.blade.php
@extends('app')
@section('title',(strlen($seoTitle) > 1 ? $seoTitle : $page->title))
@section('seo_title', (strlen($seoTitle) > 1 ? $seoTitle : $page->seo_title))
@section('meta_keywords',(strlen($keywords) > 1 ? $keywords :$page->meta_keywords))
@section('meta_description', (strlen($description) > 1 ? $description : $page->meta_description))
@section('image',env('APP_URL').'/images/og.jpg')
@section('url',url()->current())
@section('page_class','home')
@section('content')
    <div class="breadcrumbs">
        @include('partials.breadcrumbs',['title'=>$page->title])
        <h1 class="titleDark">{{$page->title}}</h1>
    </div>
    <section id="aboutUs">
        <div class="container">
            {!! $page->body !!}
            @if(count(json_decode($page->files)))
                <div class="row d-flex align-items-center">
                    @foreach (json_decode($page->files) as $file)
                        @php
                            $name = explode('/',$file)[array_key_last(explode('/',$file))];
                        @endphp
                        <div class="col-lg-4 col-md-4 col-sm-6 p-3">
                            <div class="galleryProductItem {{App\Page::mimeType($file)}}">
                                <a href="{{Voyager::image($file)}}" target="_blank">{{$name}}</a>
                            </div>
                        </div>
                    @endforeach
                </div>
            @endif
        </div>
    </section>
@endsection

resources/views/pages/thanks.blade.php
@extends('app')
@section('title','Спасибо за заявку')
@section('seo_title', 'Спасибо за заявку')
@section('meta_keywords','Спасибо за заявку')
@section('meta_description', 'Спасибо за заявку')
@section('image',env('APP_URL').'/images/og.jpg')
@section('url',url()->current())
@section('page_class','page-other')
@section('content')
    <main class="content">
        <section class="content-inner">
            <div class="container">
                <div class="text_block thanks-page">
                    <img src="/img/success.png" alt="Спасибо за заявку">
                    <h1>Спасибо за заявку, {{$_REQUEST['name']}}</h1>
                    <p>Мы свяжемся с вами в ближайшее время</p>
                    <div class="btns">
                        <a href="/" class="btn-white">Вернуться на главную</a>
                    </div>
                </div>
            </div>
        </section>
    </main><!-- .content -->
@endsection